Support for database migrations using Alembic
jgalar/CanadianTracker pull request #8
Opened 2022-03-21 00:54 UTC by simark

2022-03-21 19:13 UTC, jgalar requested changes
Otherwise the PR looks good. Thanks a lot for the detailed messages.

2022-03-21 19:13 UTC, jgalar commented on src/canadiantracker/triangle.py
> +    def __init__(self, dev_max_categories=0, dev_max_pages_per_category=0):
Please use type annotations.

There are a couple missing, but I'll remedy them.

2022-03-21 21:22 UTC, simark commented on src/canadiantracker/triangle.py
> +    def __init__(self, dev_max_categories=0, dev_max_pages_per_category=0):
Ok, fixed (I think).

2022-03-22 01:08 UTC, jgalar commented on src/canadiantracker/triangle.py
> +    def __init__(self, dev_max_categories=0, dev_max_pages_per_category=0):
Fantastic, thanks!

2022-03-22 01:08 UTC, merged